# documentation: https://github.com/marckohlbrugge/sessy/blob/main/docs/docker-deployment.md
# slogan: Email observability platform for monitoring and analyzing email systems.
# category: monitoring
# tags: email, observability, monitoring, analytics
# logo: svgs/sessy.svg
# port: 80

services:
  sessy:
    image: ghcr.io/marckohlbrugge/sessy:main
    environment:
      - SERVICE_URL_SESSY_80
      - SECRET_KEY_BASE=$SERVICE_HEX_64_SESSYSECRET
      - HTTP_AUTH_USERNAME=$SERVICE_USER_SESSY
      - HTTP_AUTH_PASSWORD=$SERVICE_PASSWORD_SESSY
    volumes:
      - sessy-data:/rails/storage
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:80 || [ $? -eq 22 ]"]
      interval: 5s
      timeout: 10s
      retries: 10
